### ISSUE TITLE
Dev environment not setting up

### ISSUE THREAD

**Issue by Razamindset** [rajput-hemant/infinitunes#59]
Hi there! I was looking to contribute to this project but encountered some issues during setup:
1. I get this error 
![image](https://github.com/user-attachments/assets/0aa9c830-3726-4823-ad1c-0eb1686c2df0)
The error indicates that a file could not be found. I want to clarify that I have set up the environment variables according to .env.example. I tried setting `SKIP_ENV_VALIDATION=true`, but that didn't help either.
I would appreciate any help regarding this issue. I've tried various solutions but haven't found one that works.

**Comment by Razamindset** [comment]
anyone?

**Comment by rajput-hemant** [comment]
Hey @Razamindset,
Thanks for your interest in contributing to the project—I really appreciate it!
I've pushed some updates and migrated to Next.js v15. Please pull the latest changes and see if that resolves the issue. Let me know if you need any further assistance!

**Comment by Razamindset** [comment]
I am on the latest code of the project. I also think it may be because of the migration but the issue still persists

**Comment by Razamindset** [comment]
My bad for that. I was able to start the server but I have to mention the experimental ppr was showing some issue so I commented it for now. The new issue is that now the api is broken the have this weired error
![image](https://github.com/user-attachments/assets/cb395ee9-8795-456f-a903-77450776cc15)
Can you give me a valid api endpoint that works..

**Comment by Razamindset** [comment]
I think it is because of the vercel security checkpoint. I will deploy my own real quick

**Comment by Razamindset** [comment]
Thank you for your support. the problem was the vercel security checkpoint it was blocking the get request on
 `https://jiosaavn-api-ts.vercel.app/`
I did had some trouble deploying on vercel and I have opened the issue on the api repo. For now I managed to use to local api server for my development. Thanks :)
